services:
  auth:
    build:
      context: ./Auth/auth
      dockerfile: ./Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production

  shipment:
    build:
      context: ./Shipment/shipment
    ports:
      - "8000:8001"  
    environment:
      - NODE_ENV=production
